### ISSUE TITLE
功能建议：增加收藏时间

### ISSUE THREAD

**Issue by DentistCode** [AHCorn/Bilibili-Favlist-Export#1]
在title、url与foldername的基础上，多加个收藏时间

**Comment by AHCorn** [comment]
之前哔哩哔哩似乎会省略掉收藏的具体时间，我最近整理过文件夹，没法验证太久远的收藏视频的显示效果。
这个 CSV 导出主要是为符合 Raindrop 应用的导入格式，作为备份而言可能会差一些，这两天会更新该新导出项。

**Comment by AHCorn** [comment]
抱歉耽搁了几天，该选项已在 2.0 版本中添加，目前我个人测试没有问题，若出现问题的话欢迎随时反馈
